# -*- coding: utf-8 -*-
"""TA_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hDnYNtT9a2JuYTkKCOBMcjcXGD-8fKpS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime
import colorama
from colorama import Fore
from colorama import Style

print("script location:", __file__)


mode = input("attend / hw : ")
if mode == "attend":
  date = input("Input the initial date (xx/xx): ") #datetime.date.today().strftime('%m/%d')
else:
  date = "hw1"

path = './112-1_物理學史出席程式用.xlsx'
file = pd.read_excel(path)
today_col = pd.DataFrame(np.zeros(np.array(file).shape[0]))
revised = pd.concat([file,today_col],axis=1)
revised.columns = ['No.','系級','學號','姓名',date]  # 最上方一行需輸入一個不重要的值，必免欄名取代
revised['學號'] = revised['學號'].astype(int)

d = 1
while d != 0:
  stid = input(Fore.YELLOW + 'Input the student id , input 0 to stop : ' + Style.RESET_ALL)
  nonint = []
  if len(list(stid)) != 0:
    for i in list(stid):
      if not i.isdigit():
        nonint.append(i)
  else:
    nonint.append(1)

  if len(nonint)!=0: 
    print(Fore.RED + Style.BRIGHT + 'ERROR! Plz check the student id!' + Style.RESET_ALL)
  elif len(nonint)==0 and int(stid)==0:
    d = 0
  else:
    filter = revised[revised["學號"] == int(stid)]
    if np.array(filter).shape[0] != 0 :
      target = np.array(revised.loc[revised['學號']==int(stid),'姓名'])[0]
      check = input(Fore.RED + 'Is %s? ENTER/n : '%target + Style.RESET_ALL)
      if len(list(check)) == 0:
        revised.loc[(revised['學號']== int(stid)) , date] = 1
      else:
        print(Fore.RED + Style.BRIGHT + 'ERROR! Plz check the student id!' + Style.RESET_ALL)
    if np.array(filter).shape[0] == 0 and d != 0:
      print(Fore.RED + Style.BRIGHT + 'ERROR! Plz check the student id!' + Style.RESET_ALL)

now = datetime.datetime.now()
serial = now.strftime("%Y-%m-%d_%H:%M:%S")

if mode == "attend":
  revised.to_excel("./112-1點名-{}.xlsx".format(serial),index=False)
else:
  revised.to_excel("./112-1點名-{}.xlsx".format(serial),index=False)
print(Fore.BLUE + Style.BRIGHT + 'The data has been saved !' + Style.RESET_ALL)
